# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: casm_runner.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'casm_runner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61sm_runner.proto\x12\x0e\x63\x61sm.runner.v1\"J\n\x0cStartRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\x0c\x12\x15\n\rartifact_root\x18\x03 \x01(\t\"\x1f\n\rStartResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"\x1f\n\rCancelRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"&\n\x0e\x43\x61ncelResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"!\n\x0fGetStateRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"\x80\x01\n\rStateResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\'\n\x05state\x18\x02 \x01(\x0e\x32\x18.casm.runner.v1.RunState\x12\x16\n\x0estatus_message\x18\x03 \x01(\t\x12\x10\n\x08sim_time\x18\x04 \x01(\x01\x12\x0c\n\x04tick\x18\x05 \x01(\x03\"G\n\x10StreamObsRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x12\n\nstart_tick\x18\x03 \x01(\x03\"<\n\x08ObsBatch\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0c\n\x04tick\x18\x02 \x01(\x03\x12\x11\n\tarrow_ipc\x18\x03 \x01(\x0c*\xa0\x01\n\x08RunState\x12\x19\n\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x1a\n\x16RUN_STATE_INITIALIZING\x10\x01\x12\x15\n\x11RUN_STATE_RUNNING\x10\x02\x12\x17\n\x13RUN_STATE_COMPLETED\x10\x03\x12\x14\n\x10RUN_STATE_FAILED\x10\x04\x12\x17\n\x13RUN_STATE_CANCELLED\x10\x05\x32\xb8\x02\n\x10SimulatorControl\x12\x44\n\x05Start\x12\x1c.casm.runner.v1.StartRequest\x1a\x1d.casm.runner.v1.StartResponse\x12G\n\x06\x43\x61ncel\x12\x1d.casm.runner.v1.CancelRequest\x1a\x1e.casm.runner.v1.CancelResponse\x12J\n\x08GetState\x12\x1f.casm.runner.v1.GetStateRequest\x1a\x1d.casm.runner.v1.StateResponse\x12I\n\tStreamObs\x12 .casm.runner.v1.StreamObsRequest\x1a\x18.casm.runner.v1.ObsBatch0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'casm_runner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNSTATE']._serialized_start=521
  _globals['_RUNSTATE']._serialized_end=681
  _globals['_STARTREQUEST']._serialized_start=37
  _globals['_STARTREQUEST']._serialized_end=111
  _globals['_STARTRESPONSE']._serialized_start=113
  _globals['_STARTRESPONSE']._serialized_end=144
  _globals['_CANCELREQUEST']._serialized_start=146
  _globals['_CANCELREQUEST']._serialized_end=177
  _globals['_CANCELRESPONSE']._serialized_start=179
  _globals['_CANCELRESPONSE']._serialized_end=217
  _globals['_GETSTATEREQUEST']._serialized_start=219
  _globals['_GETSTATEREQUEST']._serialized_end=252
  _globals['_STATERESPONSE']._serialized_start=255
  _globals['_STATERESPONSE']._serialized_end=383
  _globals['_STREAMOBSREQUEST']._serialized_start=385
  _globals['_STREAMOBSREQUEST']._serialized_end=456
  _globals['_OBSBATCH']._serialized_start=458
  _globals['_OBSBATCH']._serialized_end=518
  _globals['_SIMULATORCONTROL']._serialized_start=684
  _globals['_SIMULATORCONTROL']._serialized_end=996
# @@protoc_insertion_point(module_scope)
