# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from casmsocial.proto import casm_runner_pb2 as casm__runner__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in casm_runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulatorControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/casm.runner.v1.SimulatorControl/Start',
                request_serializer=casm__runner__pb2.StartRequest.SerializeToString,
                response_deserializer=casm__runner__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/casm.runner.v1.SimulatorControl/Cancel',
                request_serializer=casm__runner__pb2.CancelRequest.SerializeToString,
                response_deserializer=casm__runner__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/casm.runner.v1.SimulatorControl/GetState',
                request_serializer=casm__runner__pb2.GetStateRequest.SerializeToString,
                response_deserializer=casm__runner__pb2.StateResponse.FromString,
                _registered_method=True)
        self.StreamObs = channel.unary_stream(
                '/casm.runner.v1.SimulatorControl/StreamObs',
                request_serializer=casm__runner__pb2.StreamObsRequest.SerializeToString,
                response_deserializer=casm__runner__pb2.ObsBatch.FromString,
                _registered_method=True)


class SimulatorControlServicer:
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamObs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=casm__runner__pb2.StartRequest.FromString,
                    response_serializer=casm__runner__pb2.StartResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=casm__runner__pb2.CancelRequest.FromString,
                    response_serializer=casm__runner__pb2.CancelResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=casm__runner__pb2.GetStateRequest.FromString,
                    response_serializer=casm__runner__pb2.StateResponse.SerializeToString,
            ),
            'StreamObs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamObs,
                    request_deserializer=casm__runner__pb2.StreamObsRequest.FromString,
                    response_serializer=casm__runner__pb2.ObsBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'casm.runner.v1.SimulatorControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('casm.runner.v1.SimulatorControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulatorControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casm.runner.v1.SimulatorControl/Start',
            casm__runner__pb2.StartRequest.SerializeToString,
            casm__runner__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casm.runner.v1.SimulatorControl/Cancel',
            casm__runner__pb2.CancelRequest.SerializeToString,
            casm__runner__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casm.runner.v1.SimulatorControl/GetState',
            casm__runner__pb2.GetStateRequest.SerializeToString,
            casm__runner__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamObs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/casm.runner.v1.SimulatorControl/StreamObs',
            casm__runner__pb2.StreamObsRequest.SerializeToString,
            casm__runner__pb2.ObsBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
