random.seed: 42
stop.at: 24
human.count: 10
world.width: 2
world.height: 2
steps.per.day: 3
activity.file: 'data/processed/wake_county/activities.parquet'
household.file: 'data/processed/wake_county/hh.parquet'
school.file: 'data/processed/wake_county/schools.parquet'
work.file: 'data/processed/wake_county/work.parquet'
contact.file: 'data/processed/wake_county/cn.parquet'
person.file: 'data/processed/wake_county/persons.parquet'
meet_log_file: 'output/meet_log.csv'
agent_log_file: 'output/agent_log.csv'
