model.name: 'casmsocial_heatrisk_HeatRiskModel'
random.seed: 42
stop.at: 24
world.width: 2
world.height: 2
steps.per.day: 24
world.bounding.box: [682382, 65291, 3933088, 61693]
places.files:
  - data/processed/wake_county_prism_fulltest/hh.parquet
  - data/processed/wake_county_prism_fulltest/schools.parquet
  - data/processed/wake_county_prism_fulltest/work.parquet
activities.file: 'data/processed/wake_county_prism_fulltest/activities.parquet'
persons.file: 'data/processed/wake_county_prism_fulltest/persons.parquet'
heatIndex.file: 'data/processed/wake_county_test/heatIndex_by_hour_place.parquet'
meet_log_file: 'output/meet_log.csv'
heat_threshold: 90
agent_log_file: 'output/agent_log.csv'
