model.name: 'casmsocial_GeoModel'
random.seed: 42
stop.at: 24
world.width: 2
world.height: 2
steps.per.day: 24
world.bounding.box: [682382, 65291, 3933088, 61693]
place.files:
  - data/processed/wake_county/hh_sample_5000_utm.parquet
  - data/processed/wake_county/schools_sample_5000_utm.parquet
  - data/processed/wake_county/work_sample_5000_utm.parquet
activity.file: 'data/processed/wake_county/activities_sample_5000.parquet'
contact.file: 'data/processed/wake_county/cn_sample_5000.parquet'
person.file: 'data/processed/wake_county/persons_sample_5000.parquet'
heatIndex.file: 'data/processed/wake_county/heatIndex_by_hour_place.parquet'
heat_threshold: 90
meet_log_file: 'output/meet_log.csv'
agent_log_file: 'output/agent_log.csv'
