model.name: 'casmsocial.dcsim.dcsocialmodel.ArtSocModel'
random.seed: 42
stop.at: 24
world.width: 2
world.height: 2
steps.per.day: 24
places.files:
  - 'data/processed/dmv_population/hh_100.parquet'
  - 'data/processed/dmv_population/schools_100.parquet'
  - 'data/processed/dmv_population/work_100.parquet'
activities.file: 'data/processed/dmv_population/activities_100.parquet'
contacts.file: 'data/processed/dmv_population/cn_100.parquet'
persons.file: 'data/processed/dmv_population/persons_100.parquet'
agent_log_file: 'output/agent_log.csv'
