model.name: 'casmsocial.heat_risk.heat_risk_model2.HeatRiskModel2'
random.seed: 42
start.datetime: '2023-09-07 00:00:00'
duration.hours: 24
timezone: 'America/New_York'
time.step.minutes: 15
places.file: '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/abm_inputs/places.parquet'
activities.file: '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/abm_inputs/activities.parquet'
persons.file: '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/abm_inputs/persons.parquet'
environment.file: '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/abm_inputs/weather_at_places.parquet'
heat_threshold_cooling_center: 90
heat_threshold_health_effect: 100
closest_cooling_center.file: '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/abm_inputs/closest_cooling_center.parquet'
lagged_weather.file:
    '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/abm_inputs/lagged_weather.parquet'
agent_log_file: '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/output/agent_log.parquet'
run_log_file: '/projects/ARTSOC-POLICY-MODELING/bianica/test-run/data/output/run_log.parquet'
